# Generated by Django 6.0 on 2025-12-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
